In [1]:
#import libraries
import numpy as np
import pandas as pd
import re

In [2]:
df= pd.read_csv(r"/Users/ozo/Downloads/spam.csv", encoding= 'ISO-8859-1', encoding_errors = 'strict')


In [3]:
df.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [4]:
df=df.drop(df.columns[[2,3,4]], axis=1)

In [5]:
df.head()

v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [6]:
df.rename(columns={'v1': 'Label', 'v2': 'Text'}, inplace=True)

In [7]:
df.head()

Label                                               Text
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [8]:
# Acutally this data are contained huge ammount of space and dot. thats why we can use regex for given only words and numbers.
# Apply the regular expression to the "Text" column and join the results with a space
df['Text'] = df['Text'].apply(lambda x: ' '.join(re.findall(r'[A-Za-z0-9]+', str(x))))


In [9]:
df['Text'][0]

'Go until jurong point crazy Available only in bugis n great world la e buffet Cine there got amore wat'

In [10]:
# Label data are convert into a decimal number just label encoding using by lambda
df.Label=df.Label.apply(lambda x: 1 if x=="spam" else 0)

In [11]:
df.head()

Label                                               Text
0      0  Go until jurong point crazy Available only in ...
1      0                            Ok lar Joking wif u oni
2      1  Free entry in 2 a wkly comp to win FA Cup fina...
3      0        U dun say so early hor U c already then say
4      0  Nah I don t think he goes to usf he lives arou...

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
# data are divied into training and testing dataset
X_train, X_test, y_train, y_test=train_test_split(df.Text, df.Label, test_size=0.2)



In [14]:
X_train.shape


(4457,)

In [15]:
# import counvectorization for text transfrom 
from sklearn.feature_extraction.text import CountVectorizer

In [16]:
cv=CountVectorizer()

In [17]:
X_train_cv= cv.fit_transform(X_train.values)

In [18]:
X_train

4747    The beauty of life is in next second which hid...
981     Reckon need to be in town by eightish to walk ...
4145    I can t wait for cornwall Hope tonight isn t t...
1902                My sister got placed in birla soft da
200                                I sent you lt gt bucks
                              ...                        
4720                Yup Anything lor if u dun wan it s ok
1143    And is there a way you can send shade s stuff ...
619     Let there be snow Let there be snow This kind ...
3856    No But we found a diff farm shop to buy some c...
2996             Don know he is watching film in computer
Name: Text, Length: 4457, dtype: object

In [19]:
X_train_cv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [20]:
X_train_cv.shape # there are 7676 unique words are locate in our BOW

(4457, 7619)

In [21]:
cv.get_feature_names_out()[2000:2100]

array(['costing', 'costs', 'costumes', 'couch', 'cougar', 'cough',
       'could', 'coulda', 'couldn', 'count', 'countin', 'countinlots',
       'country', 'counts', 'coupla', 'couple', 'courage', 'course',
       'cousin', 'cover', 'coveragd', 'covers', 'coz', 'cozy', 'cps',
       'cr', 'cr01327bt', 'cr9', 'crab', 'crack', 'craigslist', 'crammed',
       'cramps', 'crap', 'crash', 'crashed', 'crashing', 'crave',
       'craving', 'craziest', 'crazy', 'crazyin', 'crckt', 'cream',
       'created', 'creative', 'credit', 'credited', 'credits', 'creep',
       'creepy', 'cres', 'cribbs', 'cricket', 'cricketer', 'crickiting',
       'cried', 'crisis', 'cro1327', 'crore', 'cross', 'crossing',
       'crowd', 'croydon', 'crucial', 'crucify', 'cruise', 'cruisin',
       'crushes', 'cry', 'crying', 'cs', 'csbcm4235wc1n3xx', 'csc',
       'csh11', 'cst', 'cstore', 'ctagg', 'ctargg', 'ctla', 'cts',
       'cttargg', 'ctter', 'cttergg', 'ctxt', 'cuck', 'cud', 'cuddle',
       'cuddled', 'cuddlin

In [22]:
#cv.vocabulary_
X_train_np=X_train_cv.toarray()
X_train_np[0]


array([0, 0, 0, ..., 0, 0, 0])

In [23]:
np.where(X_train_np[0]!=0)

(array([1257, 1265, 2652, 3232, 3381, 3591, 3698, 4046, 4605, 4696, 4820,
        5867, 5873, 6710, 6760, 7081, 7365, 7394, 7415, 7456]),)

In [24]:
X_train[:5]

4747    The beauty of life is in next second which hid...
981     Reckon need to be in town by eightish to walk ...
4145    I can t wait for cornwall Hope tonight isn t t...
1902                My sister got placed in birla soft da
200                                I sent you lt gt bucks
Name: Text, dtype: object

In [25]:
np.where(X_train_np[2961]!=0)

(array([ 851,  954, 1886, 3268, 3425, 3466, 4845, 6722, 6825, 7081, 7394]),)

In [26]:
X_train_np[2961][1644]

0

In [27]:
# impor Naive Bayes algorithm for prediction 
from sklearn.naive_bayes import MultinomialNB

In [28]:
NB=MultinomialNB()

In [29]:
NB.fit(X_train_cv, y_train)


MultinomialNB()

In [30]:
X_test_cv= cv.transform(X_test)

In [31]:
y_pred=NB.predict(X_test_cv)


In [32]:
from sklearn.metrics import accuracy_score, classification_report

In [33]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       961
           1       0.97      0.93      0.95       154

    accuracy                           0.99      1115
   macro avg       0.98      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115



In [34]:
print(accuracy_score(y_test, y_pred))

0.9865470852017937
